BEGIN TRANSACTION;
CREATE TABLE "user" (
	`uid`	INTEGER PRIMARY KEY AUTOINCREMENT,
	`name`	TEXT,
	`email`	TEXT NOT NULL UNIQUE,
	`password`	TEXT NOT NULL,
	`role`	INTEGER NOT NULL
);
INSERT INTO `user` VALUES (1,'Marc Muster','marc.muster@gibb.ch','42cd695e0d73e3d0b5774bcb2a0a5f09',1);
INSERT INTO `user` VALUES (2,'Hans Hinterseer','hans.hinterseer@gibb.ch','42cd695e0d73e3d0b5774bcb2a0a5f09',1);
INSERT INTO `user` VALUES (3,'Sonja Sauser','sonja.sauser@gibb.ch','42cd695e0d73e3d0b5774bcb2a0a5f09',1);
INSERT INTO `user` VALUES (4,'Anna Abegglen','anna.abegglen@gibb.ch','42cd695e0d73e3d0b5774bcb2a0a5f09',1);
CREATE TABLE `topic` (
	`tid`	INTEGER PRIMARY KEY AUTOINCREMENT,
	`uid`	INTEGER NOT NULL,
	`name`	TEXT NOT NULL,
	`description`	TEXT,
	FOREIGN KEY(`uid`) REFERENCES user(uid)
);
CREATE TABLE `entry` (
	`eid`	INTEGER PRIMARY KEY AUTOINCREMENT,
	`uid`	INTEGER NOT NULL,
	`tid`	INTEGER,
	`datetime`	INTEGER NOT NULL,
	`title`	TEXT NOT NULL,
	`content`	TEXT NOT NULL,
	`picture1`	TEXT,
	`picture2`	TEXT,
	`picture3`	TEXT,
	FOREIGN KEY(`uid`) REFERENCES `user`(`uid`),
	FOREIGN KEY(`tid`) REFERENCES `topic`(`tid`)
);
INSERT INTO `entry` VALUES (1,1,NULL,1475488707,'Lorem ipsum','Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.   

Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.   

Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.   

Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.   

Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis.   

At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, At accusam aliquyam diam diam dolore dolores duo eirmod eos erat, et nonumy sed tempor et et invidunt justo labore Stet clita ea et gubergren, kasd magna no rebum. sanctus sea sed takimata ut vero voluptua. est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat.   

Consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus.   

Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.   

Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.   

Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.   

Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo',NULL,NULL,NULL);
INSERT INTO `entry` VALUES (2,1,NULL,1475563723,'Cupcake Ipsum','Wafer dragée jelly-o donut sweet chocolate sweet soufflé. Cotton candy candy canes gingerbread chocolate cake oat cake croissant carrot cake soufflé. Marshmallow bear claw liquorice jelly-o gingerbread gingerbread cake. Gummi bears gummi bears wafer caramels tiramisu donut chocolate marshmallow. Marshmallow sweet jelly beans icing oat cake tart. Muffin pudding macaroon cake cupcake candy canes croissant muffin jelly beans. Wafer dragée soufflé dragée carrot cake gingerbread lollipop. Jujubes sugar plum donut soufflé sesame snaps muffin jelly beans candy tootsie roll. Halvah wafer soufflé pudding biscuit cake dragée oat cake. Cake chocolate cake liquorice. Powder bear claw croissant cookie croissant dragée jelly. Croissant muffin soufflé tart donut oat cake apple pie. Sweet lollipop tiramisu brownie dessert. Chocolate cake cheesecake jelly beans soufflé.

Sweet roll dragée sweet roll wafer marshmallow cotton candy liquorice. Dragée cake gingerbread lemon drops. Dragée toffee dessert. Caramels candy caramels donut lollipop carrot cake soufflé. Jelly biscuit muffin croissant. Pastry ice cream candy. Soufflé marshmallow gingerbread. Cake liquorice dessert cake biscuit ice cream. Cake ice cream pastry bear claw gummi bears. Cotton candy sesame snaps cheesecake pudding chocolate cake fruitcake gummies marshmallow apple pie. Pudding jelly halvah dessert brownie candy canes ice cream marshmallow cake. Cupcake dragée jelly-o biscuit bonbon cookie tootsie roll biscuit ice cream. Caramels danish halvah marzipan candy.

Brownie sweet roll gingerbread chocolate gummi bears fruitcake sweet cupcake fruitcake. Topping powder brownie croissant halvah jelly-o sesame snaps donut jelly beans. Powder gingerbread gummi bears dessert icing. Bonbon brownie dessert tootsie roll sugar plum wafer. Sweet roll jelly beans lollipop cupcake liquorice topping muffin cake. Cupcake marshmallow dessert cheesecake cheesecake danish bonbon. Chocolate cake macaroon apple pie cookie marshmallow sweet icing pastry. Candy lemon drops dragée cotton candy. Lollipop cotton candy pastry tart tiramisu dessert wafer lemon drops. Dragée cotton candy toffee toffee cake donut lollipop chocolate cake. Halvah danish cotton candy cotton candy sweet roll oat cake. Sesame snaps soufflé cotton candy sugar plum chupa chups candy. Fruitcake jelly-o sweet roll jelly-o macaroon.

Tiramisu icing liquorice. Donut muffin tart lemon drops topping candy canes pastry lemon drops. Dragée pastry dessert. Cake chupa chups tootsie roll. Tart jelly beans marshmallow. Chocolate icing caramels liquorice. Muffin cheesecake sugar plum. Carrot cake croissant cake cake bonbon marshmallow donut chocolate cake brownie. Jujubes macaroon gummies soufflé macaroon. Cotton candy sugar plum lemon drops pastry oat cake marzipan jujubes soufflé jelly-o. Cupcake tart danish lemon drops cookie danish jelly-o. Jelly-o pie bonbon dessert candy jelly-o lollipop chupa chups sweet. Apple pie oat cake soufflé bonbon pie marzipan jelly beans jujubes.

Brownie chocolate bar macaroon chocolate. Macaroon lemon drops danish cake pastry chocolate cookie. Halvah chocolate bar chupa chups sweet roll powder powder. Carrot cake macaroon oat cake pie chupa chups brownie dragée halvah. Toffee brownie icing marshmallow biscuit. Gummies halvah ice cream fruitcake tiramisu. Jujubes brownie macaroon. Bear claw ice cream dragée donut. Marzipan sesame snaps caramels lemon drops pastry gummi bears tart jelly-o. Pudding pastry muffin brownie sesame snaps. Icing gummi bears sweet danish jelly-o. Jelly lollipop jelly beans powder sugar plum toffee toffee ice cream cake. Jelly apple pie fruitcake soufflé danish candy danish. Chocolate bar halvah jujubes danish candy.
',NULL,NULL,NULL);
INSERT INTO `entry` VALUES (3,1,NULL,1475563761,'Zombie Ipsum','Zombie ipsum reversus ab viral inferno, nam rick grimes malum cerebro. De carne lumbering animata corpora quaeritis. Summus brains sit​​, morbo vel maleficia? De apocalypsi gorger omero undead survivor dictum mauris. Hi mindless mortuis soulless creaturas, imo evil stalking monstra adventus resi dentevil vultus comedat cerebella viventium. Qui animated corpse, cricket bat max brucks terribilem incessu zomby. The voodoo sacerdos flesh eater, suscitat mortuos comedere carnem virus. Zonbi tattered for solum oculi eorum defunctis go lum cerebro. Nescio brains an Undead zombies. Sicut malus putrid voodoo horror. Nigh tofth eliv ingdead.

Cum horribilem walking dead resurgere de crazed sepulcris creaturis, zombie sicut de grave feeding iride et serpens. Pestilentia, shaun ofthe dead scythe animated corpses ipsa screams. Pestilentia est plague haec decaying ambulabat mortuos. Sicut zeder apathetic malus voodoo. Aenean a dolor plan et terror soulless vulnerum contagium accedunt, mortui iam vivam unlife. Qui tardius moveri, brid eof reanimator sed in magna copia sint terribiles undeath legionis. Alii missing oculis aliorum sicut serpere crabs nostram. Putridi braindead odores kill and infect, aere implent left four dead.

Lucio fulci tremor est dark vivos magna. Expansis creepy arm yof darkness ulnis witchcraft missing carnem armis Kirkman Moore and Adlard caeruleum in locis. Romero morbo Congress amarus in auras. Nihil horum sagittis tincidunt, zombie slack-jawed gelida survival portenta. The unleashed virus est, et iam zombie mortui ambulabunt super terram. Souless mortuum glassy-eyed oculos attonitos indifferent back zom bieapoc alypse. An hoc dead snow braaaiiiins sociopathic incipere Clairvius Narcisse, an ante? Is bello mundi z?

In Craven omni memoria patriae zombieland clairvius narcisse religionis sunt diri undead historiarum. Golums, zombies unrelenting et Raimi fascinati beheading. Maleficia! Vel cemetery man a modern bursting eyeballs perhsaps morbi. A terrenti flesh contagium. Forsitan deadgurl illud corpse Apocalypsi, vel staggering malum zomby poenae chainsaw zombi horrifying fecimus burial ground. Indeflexus shotgun coup de poudre monstra per plateas currere. Fit de decay nostra carne undead. Poenitentiam violent zom biehig hway agite RE:dead pœnitentiam! Vivens mortua sunt apud nos night of the living dead.

Whyt zomby Ut fames after death cerebro virus enim carnis grusome, viscera et organa viventium. Sicut spargit virus ad impetum, qui supersumus flesh eating. Avium, brains guts, ghouls, unholy canum, fugere ferae et infecti horrenda monstra. Videmus twenty-eight deformis pale, horrenda daemonum. Panduntur brains portae rotting inferi. Finis accedens walking deadsentio terrore perterritus et twen tee ate daze leighter taedium wal kingdead. The horror, monstra epidemic significant finem. Terror brains sit unum viral superesse undead sentit, ut caro eaters maggots, caule nobis.',NULL,NULL,NULL);
INSERT INTO `entry` VALUES (4,1,NULL,1475563849,'Charly Sheen','So ... you know ... within that is tremendous focus, and tremendous clarity, and tremendous peace. And they''re gonna fuel the battle-cry of my deadly and dangerous secret and silent soldiers. ''Cause they''re all around you .... Anyway. Thought you were just messing with one dude. Sorry! WINNING! Um ... but I''m excited to get back ... to work. Um ... and not to completely discount what you just talked about ... It''s just that if I bring up these ... these turds ... these little losers ... there''s no reason to then bring them back into the fold, because I have real fame, and they have nothing. Because you have absolute and total resolve about your decisions. If you love with violence and you hate with violence, there''s nothing that can be questioned. It''s ... yeah ... it''s an understatement. You know, I just ... I''m sorry, man, I got magic and I got poetry in my fingertips. I''m done. I''m done. It''s on. Bring it, as I say. I ain''t hidin''. Debate me on AA right now. I have a disease? Bullshit. I cured it with my brain; with my mind. And if you''re a part of my family, I will love you violently. If you infiltrate and try to hurt my family, I will murder you violently. So if you think about it, dude, it''s like I''m 0-for-3 with marriage, with ne''er an excuse.

.... And then, I just got to add this: There was a whole firestorm yesterday about Brooke being, you know, a  art of our crew. And let me just say this ... this is all I''m gonna say about it: Where there were four ... there are now three. Goodbye, Brooke, and good luck in your travels ... you''re gonna need it ... badly... So .... You know? Dealing with soft targets, and it''s just strafing runs in my underwear before my first cup of coffee because I don''t have time for these clowns. I don''t have time for their judgment and their stupidity and .... (sighs) But like in baseball, the scoreboard doesn''t lie. Never has. So what we all have is a marriage of the heart ... of the hearts. And therefore there''s nothing in the middle. I don''t live in the middle anymore. That''s where you get slaughtered. That''s where you get embarrassed in front of the prom queen. And it''s just not an option.  Because I''m just ... um .... I don''t know. Why give an interview when you can leave a warning, you know?  I''m gonna hang out with these two smokin'' hotties and fly privately around the world. You know, it might be lonely up here, but I sure like the view, Alex. Yeah, but I can''t use the word ''sober'' because that''s a term from ''those people'', and I have cleansed myself.

And I''m ... you know ... most of the time. And this includes naps! You know, I''m an F-18, bro. And I will destroy you in the air. And I will deploy my ordinance to the ground. And, uh .... But it''s just not ... I''m not fair game. I''m not a soft target. It''s over. But I dare anyone to debate me on things. I''m done. I''m done. It''s on. Bring it, as I say. I ain''t hidin''.   Yeah. I did. Because he''s nothing shy of that. And it is his job to go out there and embarrass people. Embarrass them. Not just beat them, but embarrass them in the process. I''m gonna hang out with these two smokin'' hotties and fly privately around the world. You know, it might be lonely up here, but I sure like the view, Alex.  And that was actually, you know, one of the few compliments that clown has paid me in frickin'' almost a decade.

Yeah. I did. Because he''s nothing shy of that. And it is his job to go out there and embarrass people. Embarrass them. Not just beat them, but embarrass them in the process. Well, I think it was Nails that said I was really, really flattered, ''cause he got it right. And I''m not ... Yeah, I sat with two - hey, coincidence - F-18, Top Gun, radical fire, napalm dropping pilots in my movie theater watching the chopper attack sequence on the beachhead to go surfing because they wanted to and those people were in their way.   But like in baseball, the scoreboard doesn''t lie. Never has. So what we all have is a marriage of the heart ... of the hearts. Because you have absolute and total resolve about your decisions. If you love with violence and you hate with violence, there''s nothing that can be questioned.

And Alex, try to get your mind around this, as a fellow warrior, deep in the trenches: Their entire manifesto is built upon complete and total surrender ... or the concept of complete and total surrender. .... And then, I just got to add this: There was a whole firestorm yesterday about Brooke being, you know, a part of our crew. And let me just say this ... this is all I''m gonna say about it: Where there were four ... there are now three. Goodbye, Brooke, and good luck in your travels ... you''re gonna need it ... badly... So ....  Yeah, I didn''t care about that vanity card. In fact, I went straight on with that one and just dispelled that one.  But there''s also ... falling from it ... is the apple from The Giving Tree. There''s my life. Deal with it. Oh, wait! Can''t process it. Losers! WINNING! B''bye. No. She''s not there now. They urge you to put down your sword and come join the winners. In 22 years the only ''winners'' I could locate in their toothless warren were either driving a convertible van or living like trolls under an abandoned bridge.

But ... whatever. I agreed to do it. There''s just one deal point that Jim Robinson - a wonderful man at Morgan Creek, a great company - need to work out is they want me in it. If they do, it''s a smash. If they don''t, it''s a turd that opens on a tugboat. No. She''s not there now. And one of those stupid mottoes, Alex, is ''Don''t be special. Be one of us.'' News flash! I am special, and I''ll never be one of you! ... There it is. You know? Dealing with soft targets, and it''s just strafing runs in my underwear before my first cup of coffee because I don''t have time for these clowns. I don''t have time for their judgment and their stupidity and .... (sighs)  And one of those stupid mottoes, Alex, is ''Don''t be special. Be one of us.'' News flash! I am special, and I''ll never be one of you! ... There it is. And one of those stupid mottoes, Alex, is ''Don''t be special. Be one of us.'' News flash! I am special, and I''ll never be one of you! ... There it is. They urge you to put down your sword and come join the winners. In 22 years the only ''winners'' I could locate in their toothless warren were either driving a convertible van or living like trolls under an abandoned bridge. I just closed my eyes and in a nanosecond I cured myself from this ridiculous model of disease, addiction, and obsession. It''s just ... It''s just the work of sissies.
',NULL,NULL,NULL);
INSERT INTO `entry` VALUES (5,4,NULL,1478014785,'Bacon Ipsum','Bacon ipsum dolor amet drumstick picanha ground round beef ribs swine ham. Sausage frankfurter prosciutto shank swine turducken strip steak kevin tail beef ribs shoulder pork chop jowl. Pork loin brisket alcatra sausage, andouille jowl prosciutto tenderloin. Pork loin beef ribs tenderloin turkey meatball picanha.

Beef ribs fatback bresaola, short loin pork loin tail porchetta bacon kevin picanha. Prosciutto tail salami, short ribs fatback chuck kielbasa drumstick pancetta rump meatloaf pork belly frankfurter brisket. Swine pork belly turkey landjaeger ground round. Pig bacon turkey ham, chicken salami porchetta ground round jowl tri-tip rump. Tail flank frankfurter tenderloin spare ribs shank filet mignon meatloaf pancetta ham hock chicken drumstick alcatra andouille. Brisket beef ribs biltong, frankfurter turkey short ribs bacon tongue tail alcatra pancetta corned beef short loin jowl pork.

Kevin capicola frankfurter, ham short ribs salami porchetta ball tip beef ribs shoulder ribeye spare ribs jerky beef. Spare ribs ground round pancetta, tri-tip corned beef boudin short ribs kevin strip steak turducken ham tenderloin sausage shankle pastrami. Spare ribs kevin hamburger tri-tip ground round kielbasa jerky corned beef boudin capicola swine. Beef ball tip bacon ground round, corned beef cow chuck turducken jowl pork belly venison.

Capicola sausage tri-tip venison salami. Landjaeger kevin meatball, burgdoggen bresaola shankle cupim t-bone jowl frankfurter corned beef ham hock. Kevin drumstick meatball frankfurter, short ribs tri-tip meatloaf tongue ground round ham. Biltong salami chicken pig sausage kevin. Leberkas chicken sirloin, shoulder t-bone tongue sausage.

Drumstick flank alcatra pork loin pastrami spare ribs short loin cupim shank boudin shoulder t-bone venison. Ground round ham andouille, pig flank t-bone boudin short ribs brisket tri-tip. Ribeye strip steak corned beef, turducken ham beef sausage beef ribs ground round biltong bresaola prosciutto porchetta pork belly shankle. Beef ball tip jowl meatloaf shankle sausage fatback short loin. Beef pig picanha hamburger spare ribs tri-tip fatback frankfurter chuck brisket. Pork belly alcatra salami swine, jowl pork loin tail. Drumstick capicola alcatra, pastrami ham hock short ribs hamburger turducken spare ribs ball tip pork chop.',NULL,NULL,NULL);
INSERT INTO `entry` VALUES (6,2,NULL,1478014932,'Hipster Ipsum','Neutra truffaut blog, 90''s microdosing gochujang fingerstache helvetica etsy. Shoreditch fashion axe tote bag wayfarers normcore, freegan hot chicken sriracha 8-bit brunch actually live-edge quinoa. Trust fund sustainable forage tilde, etsy gentrify 8-bit poutine blog swag lomo pug. Truffaut ugh pinterest, umami tofu hoodie cronut. Crucifix skateboard single-origin coffee, vape slow-carb pork belly direct trade everyday carry photo booth schlitz venmo franzen. Air plant viral stumptown pabst disrupt. Readymade mumblecore tumeric kitsch hashtag, godard trust fund.

Ramps brooklyn pickled echo park unicorn pop-up, succulents church-key keffiyeh af wayfarers williamsburg fap disrupt synth. Selfies blog cliche kickstarter organic tumblr freegan biodiesel slow-carb. VHS sartorial cliche, retro poke unicorn biodiesel tacos church-key kale chips crucifix. Craft beer aesthetic godard, ennui vegan you probably haven''t heard of them distillery fixie edison bulb. Banh mi artisan sartorial street art. Chillwave cold-pressed narwhal slow-carb. Lyft gluten-free marfa, chillwave mumblecore stumptown meggings meh artisan viral.

Food truck jean shorts cronut enamel pin. Franzen 3 wolf moon whatever blue bottle. Leggings polaroid lumbersexual activated charcoal, craft beer drinking vinegar XOXO locavore helvetica scenester vice lo-fi. Leggings cold-pressed yuccie affogato YOLO, VHS selfies iPhone la croix normcore tbh. Vape air plant lo-fi biodiesel affogato. Kickstarter cornhole disrupt affogato listicle locavore. Echo park meh vexillologist schlitz craft beer, letterpress mustache flannel kombucha raclette celiac bespoke hashtag vice.

PBR&B mustache beard drinking vinegar. Keytar retro locavore, vice pop-up biodiesel tousled microdosing viral. Jianbing typewriter hot chicken vinyl umami. Four loko master cleanse trust fund forage helvetica banh mi. Skateboard lyft everyday carry seitan, hot chicken vexillologist crucifix selvage shabby chic. Fashion axe echo park air plant asymmetrical. Bicycle rights photo booth cornhole keffiyeh.',NULL,NULL,NULL);
INSERT INTO `entry` VALUES (7,3,NULL,1478015026,'Tuna Ipsum','Paradise fish Australian grayling soapfish largenose fish man-of-war fish Cornish Spaktailed Bream yellow-and-black triplefin northern pike gibberfish, sailback scorpionfish triplefin blenny. Stoneroller minnow pleco; climbing catfish warmouth; Old World rivuline flounder duckbilled barracudina arapaima. Hog sucker glassfish Oregon chub fire bar danio tiger shovelnose catfish. Angler lookdown catfish weasel shark mackerel shark butterflyfish cutthroat eel Atlantic salmon sand stargazer. Dusky grouper steelhead chimaera sea chub Atlantic trout brook lamprey fierasfer. Gulper squirrelfish Cornish Spaktailed Bream damselfish limia gudgeon, cavefish. Amago. Riffle dace? Japanese eel Asian carps bat ray sea lamprey pickerel great white shark queen parrotfish plaice, sprat parasitic catfish Black swallower. Yellowfin surgeonfish snailfish brook trout rudd banded killifish, yellowfin croaker; swampfish smelt-whiting alligatorfish zebra lionfish bigscale fish halfmoon! Spookfish, European eel pike eel European flounder.

Rasbora sharksucker; fierasfer galjoen fish Chinook salmon galjoen fish Hammerjaw tripod fish. Trumpetfish sea dragon nurse shark mummichog Pacific viperfish brook trout ponyfish? Nurse shark, upside-down catfish.

Sergeant major dragonfish yellowfin surgeonfish; sand tilefish blue shark shovelnose sturgeon scaleless black dragonfish. Blind shark straptail bobtail snipe eel velvetfish bowfin sand dab, crocodile shark. Silver driftfish longnose whiptail catfish menhaden Black prickleback pupfish spaghetti eel loweye catfish northern Stargazer. Scabbard fish dealfish Blind goby, eel cod snapper; delta smelt. Threadfin bream, goldspotted killifish cat shark pupfish pickerel brook lamprey greeneye Sacramento blackfish toadfish Blacksmelt sockeye salmon. Sea catfish, crucian carp scaleless black dragonfish; tadpole fish turkeyfish weasel shark. Pygmy sunfish hoki lamprey sauger, Asiatic glassfish, "dusky grouper crevice kelpfish paperbone yellow weaver."

Knifejaw, "rivuline dragonet; deep sea bonefish triggerfish brook lamprey." Pacific salmon bass shovelnose sturgeon cichlid conger eel bream temperate ocean-bass Black pickerel? Dartfish roanoke bass springfish kokopu jewel tetra, rudderfish grass carp, gray eel-catfish Gila trout.

Sea raven smooth dogfish, basking shark skipping goby ballan wrasse electric ray great white shark. Atlantic eel round herring; Atlantic saury. European perch; tube-snout wels catfish jawfish marlin algae eater clown triggerfish Reedfish. Crappie flier New Zealand smelt, fire bar danio mudminnow dace bowfin white marlin powen.
',NULL,NULL,NULL);
CREATE TABLE `comment` (
	`cid`	INTEGER PRIMARY KEY AUTOINCREMENT,
	`eid`	INTEGER NOT NULL,
	`datetime`	INTEGER NOT NULL,
	`name`	TEXT,
	`content`	TEXT NOT NULL,
	FOREIGN KEY(`eid`) REFERENCES `entry`(`eid`)
);
COMMIT;
